services:
  - type: web
    name: app
    env: docker
    buildCommand: "docker build -t app ."
    startCommand: "gunicorn app:app -b 0.0.0.0:5000"
    plan: free
    branch: main
    autoDeploy: true
